# Generated by Django 4.2 on 2024-11-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_description',
            field=models.TextField(default=True),
        ),
    ]
